/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WordGameForms;

import DI.SingleConnection;
import beans.Competitor;
import database.CompetitorDatabase;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alizaman
 */
public class AdminPanelForm extends javax.swing.JFrame {

    Connection conn = SingleConnection.getSingleConnect();
    CompetitorDatabase competitorDatabase = new CompetitorDatabase();

    /**
     * Creates new form AdminPanelForm
     */
    public AdminPanelForm() {
        initComponents();
        tblCompetitor.getTableHeader().setReorderingAllowed(false);
        tblCompetitor.getTableHeader().setBackground(new Color(80, 127, 127));
        tblCompetitor.getTableHeader().setForeground(Color.WHITE);
        tblCompetitor.getTableHeader().setFont(new Font("Times New Roman", Font.PLAIN, 14));
        refreshTable(competitorDatabase.competitorInfo(conn));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblAdminPanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompetitor = new javax.swing.JTable();
        btnEdir = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 140, 0));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        lblClose.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("x");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblClose.setPreferredSize(new java.awt.Dimension(18, 51));
        lblClose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCloseMouseMoved(evt);
            }
        });
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });

        lblMin.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblMin.setForeground(new java.awt.Color(255, 255, 255));
        lblMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMin.setText("_");
        lblMin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblMin.setPreferredSize(new java.awt.Dimension(13, 51));
        lblMin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMinMouseMoved(evt);
            }
        });
        lblMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinMouseExited(evt);
            }
        });

        lblAdminPanel.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        lblAdminPanel.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminPanel.setText("AdminPanel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblAdminPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdminPanel))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(47, 79, 79));

        tblCompetitor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblCompetitor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblCompetitor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblCompetitor.setColumnSelectionAllowed(true);
        tblCompetitor.setFocusable(false);
        tblCompetitor.setGridColor(new java.awt.Color(102, 102, 102));
        tblCompetitor.setSelectionBackground(new java.awt.Color(255, 140, 0));
        tblCompetitor.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblCompetitor.setShowVerticalLines(false);
        tblCompetitor.getTableHeader().setResizingAllowed(false);
        tblCompetitor.getTableHeader().setReorderingAllowed(false);
        tblCompetitor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCompetitorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCompetitor);

        btnEdir.setBackground(new java.awt.Color(0, 102, 0));
        btnEdir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEdir.setForeground(new java.awt.Color(255, 255, 255));
        btnEdir.setText("Edit");
        btnEdir.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        btnEdir.setFocusPainted(false);
        btnEdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdirActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(153, 0, 0));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        btnDelete.setFocusPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEdir, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdir)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseExited
        lblMin.setBackground(new Color(255, 140, 0));
        lblMin.setOpaque(true);
    }//GEN-LAST:event_lblMinMouseExited

    private void lblMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseClicked
        this.setState(LoginForm.ICONIFIED);
    }//GEN-LAST:event_lblMinMouseClicked

    private void lblMinMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseMoved
        lblMin.setBackground(new Color(255, 100, 0));
        lblMin.setOpaque(true);
    }//GEN-LAST:event_lblMinMouseMoved

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setBackground(new Color(255, 140, 0));
        lblClose.setOpaque(true);
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        this.dispose();
        CompetitorForm competitorForm = new CompetitorForm();
        competitorForm.setVisible(true);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseMoved
        lblClose.setBackground(Color.RED);
        lblClose.setOpaque(true);
    }//GEN-LAST:event_lblCloseMouseMoved
    int x, y, x1, y1;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getXOnScreen();
        y = evt.getYOnScreen();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        x1 = evt.getXOnScreen();
        y1 = evt.getYOnScreen();
        this.setLocation(this.getX() + x1 - x, this.getY() + y1 - y);
        x = x1;
        y = y1;
    }//GEN-LAST:event_jPanel1MouseDragged

    private void btnEdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdirActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Əminmiziniz?", "", JOptionPane.YES_NO_OPTION) == 0) {
            List<Competitor.CompetitorInfo> competitorInfos = competitorDatabase.competitorInfo(conn);
            for (int i = 0; i < tblCompetitor.getRowCount(); i++) {
                if ((Boolean) tblCompetitor.getValueAt(i, 4) != competitorInfos.get(i).isPosition()) {
                    competitorInfos.get(i).setPosition(!competitorInfos.get(i).isPosition());
                    competitorDatabase.updateCompetitorInfo(competitorInfos.get(i).getId(), competitorInfos.get(i).isPosition(), conn);
                }
            }
            refreshTable(competitorDatabase.competitorInfo(conn));
        }
    }//GEN-LAST:event_btnEdirActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Silməy istədiyinizdən əminmisiniz?", "", JOptionPane.YES_NO_OPTION) == 0) {
            try {
                int id = (int) tblCompetitor.getValueAt(tblCompetitor.getSelectedRow(), 0);
//                System.out.println(id);
            competitorDatabase.delete(id, conn);
            refreshTable(competitorDatabase.competitorInfo(conn));
            } catch (Exception ex) {

            }

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblCompetitorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCompetitorMouseClicked
        if (evt.getClickCount() == 2) {
            tblCompetitor.setColumnSelectionInterval(0, tblCompetitor.getColumnCount() - 1);
        }
    }//GEN-LAST:event_tblCompetitorMouseClicked

    private void refreshTable(List list) {
        List<Competitor.CompetitorInfo> competitorInfos = list;

        Object[] columnName = {"Id", "Name", "Surname", "Point", "Position"};

        Object[][] data = new Object[competitorInfos.size()][columnName.length];
        for (int i = 0; i < competitorInfos.size(); i++) {
            data[i][0] = competitorInfos.get(i).getId();
            data[i][1] = competitorInfos.get(i).getName();
            data[i][2] = competitorInfos.get(i).getSurname();
            data[i][3] = competitorInfos.get(i).getPoint();
            data[i][4] = competitorInfos.get(i).isPosition();
        }

        tblCompetitor.setModel(new DefaultTableModel(data, columnName) {

            @Override
            public boolean isCellEditable(int row, int column) {
                if (column == 4) {
                    return true;
                }
                return false;
            }

            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                        return Integer.class;
                    case 3:
                        return Integer.class;
                    case 4:
                        return Boolean.class;
                    default:
                        return String.class;
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanelForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdminPanel;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMin;
    private javax.swing.JTable tblCompetitor;
    // End of variables declaration//GEN-END:variables
}
